# Python Fundamentals

# Session 9

# Data Profiling
Before cleaning the data, profile the dataset and provide your notes.
Find the number of rows and columns.
1) Display the column names and data types.
2) Check the number of null values in each column.
3) Check the number of duplicate rows.
4) Display basic statistical information.
5) Identify any unnecessary or suspicious data.
6) Write your observations before handling the data.

In [1]:
import pandas as pd

1) Display the column names and data types.

In [2]:
df = pd.read_csv('SuperMarket.csv')
df

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.22,3/8/2019,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.048,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,NaN,10:37:00 AM,E-wallet,604.17,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1009,886-18-2897,Alex,Yangon,Normal,Female,Food and beverages,56.56,5,14.1400,296.94,3/22/2019,7:06:00 PM,Credit card,282.80,4.761905,14.1400,4.5
1010,602-16-6955,Cairo,Mandalay,Normal,Female,Sports and travel,76.60,10,38.3000,804.3,1/24/2019,6:10:00 PM,Ewallet,766.00,4.761905,38.3000,6.0
1011,745-74-0715,Alex,Yangon,Normal,Male,Electronic accessories,58.03,2,5.8030,121.863,3/10/2019,8:46:00 PM,Ewallet,116.06,4.761905,5.8030,8.8
1012,690-01-6631,Cairo,Mandalay,Normal,Male,Fashion accessories,17.49,10,8.7450,183.645,2/22/2019,6:35:00 PM,Ewallet,174.90,4.761905,8.7450,6.6
1013,652-49-6720,Giza,Naypyitaw,Member,Female,Electronic accessories,60.95,1,3.0475,63.9975,2/18/2019,11:40:00 AM,Ewallet,60.95,4.761905,3.0475,5.9

In [3]:
print(df.columns)
print(df.dtypes)

Index(['Invoice ID', 'Branch', 'City', '   Customer type', 'Gender',
       'Product line', 'Unit price', 'Quantity', 'Tax 5%', 'Sales', 'Date',
       'Time', 'Payment    ', '   cogs', 'gross margin percentage',
       'gross income', 'Rating'],
      dtype='object')
Invoice ID                  object
Branch                      object
City                        object
   Customer type            object
Gender                      object
Product line                object
Unit price                 float64
Quantity                     int64
Tax 5%                     float64
Sales                       object
Date                        object
Time                        object
Payment                     object
   cogs                    float64
gross margin percentage    float64
gross income               float64
Rating                     float64
dtype: object

2) Check the number of null values in each column.

In [4]:
df.isnull().sum()

Invoice ID                  0
Branch                      0
City                        0
   Customer type            0
Gender                      0
Product line                0
Unit price                 24
Quantity                    0
Tax 5%                      0
Sales                      20
Date                       12
Time                        0
Payment                     0
   cogs                     0
gross margin percentage     0
gross income                0
Rating                      0
dtype: int64

3) Check the number of duplicate rows.

In [5]:
df.duplicated().sum()

14

4) Display basic statistical information.

In [6]:
df.describe()

,Unit price,Quantity,Tax 5%,cogs,gross margin percentage,gross income,Rating
count,990.000000,1014.000000,1014.000000,1014.000000,1014.000000,1014.000000,1014.000000
mean,55.520333,5.502959,15.336872,306.737436,4.761905,15.336872,6.960454
std,26.330508,2.927133,11.685945,233.718896,0.000000,11.685945,1.721264
min,10.080000,1.000000,0.508500,10.170000,4.761905,0.508500,4.000000
25%,33.202500,3.000000,5.864625,117.292500,4.761905,5.864625,5.500000
50%,54.890000,5.000000,12.066000,241.320000,4.761905,12.066000,6.900000
75%,77.667500,8.000000,22.428000,448.560000,4.761905,22.428000,8.475000
max,99.960000,10.000000,49.650000,993.000000,4.761905,49.650000,10.000000

5) Identify any unnecessary or suspicious data.

6) Write your observations before handling the data.

# Data Cleaning
1) Rename the columns using clear and readable names.
2) Handle missing values when necessary.
3) Remove duplicate rows.
4) Remove unnecessary columns.
5) Make sure all columns have the correct data types.
6) Sort the data where appropriate.
7) Create a new 3 columns Day, Month, Year
8) Create a new column called satisfied based on rating.
Satisfied rule: rating >= 7 → Satisfied Else Not Satisfied

1) Rename the columns using clear and readable names.

In [7]:
df.columns = df.columns.str.strip()

2) Handle missing values when necessary.

In [8]:
df.isnull().sum()

Invoice ID                  0
Branch                      0
City                        0
Customer type               0
Gender                      0
Product line                0
Unit price                 24
Quantity                    0
Tax 5%                      0
Sales                      20
Date                       12
Time                        0
Payment                     0
cogs                        0
gross margin percentage     0
gross income                0
Rating                      0
dtype: int64

In [9]:
df['Unit price'] = df['Unit price'].fillna(df['cogs'] / df['Quantity'])
df['Sales'] = df['Sales'].str.replace('EGP', '').astype('float')
df['Sales'] = df['Sales'].fillna(df['cogs'] * 1.05)
df = df.dropna(subset=['Date'])

In [10]:
df.isnull().sum()

Invoice ID                 0
Branch                     0
City                       0
Customer type              0
Gender                     0
Product line               0
Unit price                 0
Quantity                   0
Tax 5%                     0
Sales                      0
Date                       0
Time                       0
Payment                    0
cogs                       0
gross margin percentage    0
gross income               0
Rating                     0
dtype: int64

3) Remove duplicate rows.

In [11]:
df = df.drop_duplicates()

4) Remove unnecessary columns.

In [12]:
df = df.drop(columns=['Tax 5%', 'gross income', 'gross margin percentage'])
df

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Sales,Date,Time,Payment,cogs,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,80.2200,3/8/2019,10:29:00 AM,Cash,76.40,9.6
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,340.5255,3/3/2019,1:23:00 PM,Credit card,324.31,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,489.0480,1/27/2019,8:33:00 PM,Ewallet,465.76,8.4
16,656-95-9349,Alex,Yangon,Member,Female,Health and beauty,68.93,7,506.6355,3/11/2019,11:03:00 AM,Credit card,482.51,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,Giza,Naypyitaw,Normal,Male,Health and beauty,40.35,1,42.3675,1/29/2019,1:46:00 PM,Ewallet,40.35,6.2
996,303-96-2227,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,1022.4900,3/2/2019,5:16:00 PM,Ewallet,973.80,4.4
997,727-02-1313,Alex,Yangon,Member,Male,Food and beverages,31.84,1,33.4320,2/9/2019,1:22:00 PM,Cash,31.84,7.7
998,347-56-2442,Alex,Yangon,Normal,Male,Home and lifestyle,65.82,1,69.1110,2/22/2019,3:33:00 PM,Cash,65.82,4.1
999,849-09-3807,Alex,Yangon,Member,Female,Fashion accessories,88.34,7,649.2990,2/18/2019,1:28:00 PM,Cash,618.38,6.6

5) Make sure all columns have the correct data types.

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 988 entries, 0 to 999
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Invoice ID     988 non-null    object
 1   Branch         988 non-null    object
 2   City           988 non-null    object
 3   Customer type  988 non-null    object
 4   Gender         988 non-null    object
 5   Product line   988 non-null    object
 6   Unit price     988 non-null    float64
 7   Quantity       988 non-null    int64
 8   Sales          988 non-null    float64
 9   Date           988 non-null    object
 10  Time           988 non-null    object
 11  Payment        988 non-null    object
 12  cogs           988 non-null    float64
 13  Rating         988 non-null    float64
dtypes: float64(4), int64(1), object(9)
memory usage: 115.8+ KB

In [14]:
df['Date'] = pd.to_datetime(df['Date'])
df['Branch'] = df['Branch'].str.strip().str.lower()
df['Payment'] = df['Payment'].str.strip().str.lower()

cat_cols = ['Branch', 'City', 'Customer type', 'Gender', 'Product line', 'Payment']

df[cat_cols] = df[cat_cols].astype('category')

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 988 entries, 0 to 999
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Invoice ID     988 non-null    object
 1   Branch         988 non-null    category
 2   City           988 non-null    category
 3   Customer type  988 non-null    category
 4   Gender         988 non-null    category
 5   Product line   988 non-null    category
 6   Unit price     988 non-null    float64
 7   Quantity       988 non-null    int64
 8   Sales          988 non-null    float64
 9   Date           988 non-null    datetime64[ns]
 10  Time           988 non-null    object
 11  Payment        988 non-null    category
 12  cogs           988 non-null    float64
 13  Rating         988 non-null    float64
dtypes: category(6), datetime64[ns](1), float64(4), int64(1), object(2)
memory usage: 76.2+ KB

6) Sort the data where appropriate.

7) Create a new 3 columns Day, Month, Year

In [16]:
df['day'] = df['Date'].dt.day
df['month'] = df['Date'].dt.month
df['year'] = df['Date'].dt.year
df['Profit'] = df['Sales'] - df['cogs']
df

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Sales,Date,Time,Payment,cogs,Rating,day,month,year,Profit
0,750-67-8428,alex,Yangon,Member,Female,Health and beauty,74.69,7,548.9715,2019-01-05,1:08:00 PM,ewallet,522.83,9.1,5,1,2019,26.1415
1,226-31-3081,giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,80.2200,2019-03-08,10:29:00 AM,cash,76.40,9.6,8,3,2019,3.8200
2,631-41-3108,alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,340.5255,2019-03-03,1:23:00 PM,credit card,324.31,7.4,3,3,2019,16.2155
3,123-19-1176,alex,Yangon,Member,Female,Health and beauty,58.22,8,489.0480,2019-01-27,8:33:00 PM,ewallet,465.76,8.4,27,1,2019,23.2880
16,656-95-9349,alex,Yangon,Member,Female,Health and beauty,68.93,7,506.6355,2019-03-11,11:03:00 AM,credit card,482.51,4.6,11,3,2019,24.1255
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,giza,Naypyitaw,Normal,Male,Health and beauty,40.35,1,42.3675,2019-01-29,1:46:00 PM,ewallet,40.35,6.2,29,1,2019,2.0175
996,303-96-2227,cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,1022.4900,2019-03-02,5:16:00 PM,ewallet,973.80,4.4,2,3,2019,48.6900
997,727-02-1313,alex,Yangon,Member,Male,Food and beverages,31.84,1,33.4320,2019-02-09,1:22:00 PM,cash,31.84,7.7,9,2,2019,1.5920
998,347-56-2442,alex,Yangon,Normal,Male,Home and lifestyle,65.82,1,69.1110,2019-02-22,3:33:00 PM,cash,65.82,4.1,22,2,2019,3.2910
999,849-09-3807,alex,Yangon,Member,Female,Fashion accessories,88.34,7,649.2990,2019-02-18,1:28:00 PM,cash,618.38,6.6,18,2,2019,30.9190

8) Create a new column called satisfied based on rating.
- Satisfied rule: rating >= 7 → Satisfied Else Not Satisfied

In [17]:
df['satisfied'] = df['Rating'].apply(lambda x: True if x >= 7 else False)
df

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Sales,Date,Time,Payment,cogs,Rating,day,month,year,Profit,satisfied
0,750-67-8428,alex,Yangon,Member,Female,Health and beauty,74.69,7,548.9715,2019-01-05,1:08:00 PM,ewallet,522.83,9.1,5,1,2019,26.1415,True
1,226-31-3081,giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,80.2200,2019-03-08,10:29:00 AM,cash,76.40,9.6,8,3,2019,3.8200,True
2,631-41-3108,alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,340.5255,2019-03-03,1:23:00 PM,credit card,324.31,7.4,3,3,2019,16.2155,True
3,123-19-1176,alex,Yangon,Member,Female,Health and beauty,58.22,8,489.0480,2019-01-27,8:33:00 PM,ewallet,465.76,8.4,27,1,2019,23.2880,True
16,656-95-9349,alex,Yangon,Member,Female,Health and beauty,68.93,7,506.6355,2019-03-11,11:03:00 AM,credit card,482.51,4.6,11,3,2019,24.1255,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,giza,Naypyitaw,Normal,Male,Health and beauty,40.35,1,42.3675,2019-01-29,1:46:00 PM,ewallet,40.35,6.2,29,1,2019,2.0175,False
996,303-96-2227,cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,1022.4900,2019-03-02,5:16:00 PM,ewallet,973.80,4.4,2,3,2019,48.6900,False
997,727-02-1313,alex,Yangon,Member,Male,Food and beverages,31.84,1,33.4320,2019-02-09,1:22:00 PM,cash,31.84,7.7,9,2,2019,1.5920,True
998,347-56-2442,alex,Yangon,Normal,Male,Home and lifestyle,65.82,1,69.1110,2019-02-22,3:33:00 PM,cash,65.82,4.1,22,2,2019,3.2910,False
999,849-09-3807,alex,Yangon,Member,Female,Fashion accessories,88.34,7,649.2990,2019-02-18,1:28:00 PM,cash,618.38,6.6,18,2,2019,30.9190,False

# Data Analysis
The business has some questions that we need to answer. You can use
Matplotlib, Seaborn, or Streamlit to make the results more visual and
easier to understand.
1) Provide the total revenue generated by the supermarket.
2) Provide the total revenue by city and identify the city with the highest
revenue.
3) Provide the total profit by branch and identify the most profitable
branch.
4) Provide the total revenue and profit by product category and identify
the top-performing category.
5) Provide the total spending by customer type and identify which
customer type spends more.
6) Provide the number of transactions by payment method and identify
the most popular payment method.
7) Provide the average transaction value for the supermarket.
8) Provide the customer satisfaction percentage by branch and identify
the branch with the highest satisfaction.
9) Provide the total revenue by day and by month and identify the day
and month with the highest sales.
10) Provide the overall percentage of satisfied customers/transactions.

1) Provide the total revenue generated by the supermarket.

In [18]:
df['Sales'].sum().round(2)

318041.92

2) Provide the total revenue by city and identify the city with the highest
revenue.

In [19]:
city_sales = (
    df.groupby('City')['Sales']
    .sum().round(2).sort_values(ascending=False)
)
print(city_sales)
city_sales.index[0]

City
Naypyitaw    109168.71
Mandalay     105266.53
Yangon       103606.68
Name: Sales, dtype: float64

C:\Users\engmo\AppData\Local\Temp\ipykernel_20084\3796268931.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('City')['Sales']

'Naypyitaw'

3) Provide the total profit by branch and identify the most profitable
branch.

In [20]:
branch_profit = (
    df.groupby('Branch')['Profit']
    .sum().round(2).sort_values(ascending=False)
)
print(branch_profit)
branch_profit.index[0]

Branch
giza     5198.51
cairo    5012.69
alex     4933.65
Name: Profit, dtype: float64

C:\Users\engmo\AppData\Local\Temp\ipykernel_20084\2926007204.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('Branch')['Profit']

'giza'

4) Provide the total revenue and profit by product category and identify
the top-performing category.

In [21]:
product_sales = (
    df.groupby('Product line')[['Sales', 'Profit']]
    .sum().round(2).sort_values(by='Sales', ascending=False)
)
print(product_sales)
product_sales.index[0]

                           Sales   Profit
Product line
Food and beverages      55518.60  2643.74
Fashion accessories     54245.08  2583.10
Sports and travel       53898.01  2566.57
Home and lifestyle      53089.53  2528.07
Electronic accessories  52922.59  2520.12
Health and beauty       48368.10  2303.24

C:\Users\engmo\AppData\Local\Temp\ipykernel_20084\282752230.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('Product line')[['Sales', 'Profit']]

'Food and beverages'

5) Provide the total spending by customer type and identify which
customer type spends more.

In [22]:
customer_sales = (
    df.groupby('Customer type')['Sales']
    .sum().round(2).sort_values(ascending=False)
)
print(customer_sales)
customer_sales.index[0]

Customer type
Member    184769.94
Normal    133271.98
Name: Sales, dtype: float64

C:\Users\engmo\AppData\Local\Temp\ipykernel_20084\2647349900.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('Customer type')['Sales']

'Member'

6) Provide the number of transactions by payment method and identify
the most popular payment method.

In [23]:
customer_sales = (
    df.groupby('Payment')['Payment']
    .count()
)
print(customer_sales)
customer_sales.index[0]

Payment
cash           341
credit card    309
ewallet        338
Name: Payment, dtype: int64

C:\Users\engmo\AppData\Local\Temp\ipykernel_20084\2988908817.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('Payment')['Payment']

'cash'

7) Provide the average transaction value for the supermarket.

In [24]:
df['Sales'].mean().round(2)

321.9

8) Provide the customer satisfaction percentage by branch and identify
the branch with the highest satisfaction.

In [25]:
branch_satisfaction = (
    df.groupby('Branch')['satisfied']
    .mean().mul(100)
    .round(2)
    .sort_values(ascending=False)
)

print(branch_satisfaction)
print(branch_satisfaction.index[0])

Branch
alex     52.69
giza     52.15
cairo    46.04
Name: satisfied, dtype: float64
alex

C:\Users\engmo\AppData\Local\Temp\ipykernel_20084\714106635.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('Branch')['satisfied']

9) Provide the total revenue by day and by month and identify the day
and month with the highest sales.

In [26]:
month_day_sales = (
    df.groupby(['month', 'day'])['Sales']
    .sum().round(2).sort_values(ascending=False)
)
print(month_day_sales)
print(f"Month: {month_day_sales.index[0][0]}, Day: {month_day_sales.index[0][1]}")

month  day
3      9      7366.91
       14     7214.63
2      15     6830.79
       7      6774.72
3      2      6560.31
               ...
2      18     1496.03
3      7      1438.26
2      21     1393.74
3      18     1292.83
2      13      934.24
Name: Sales, Length: 89, dtype: float64
Month: 3, Day: 9

10) Provide the overall percentage of satisfied customers/transactions.

In [27]:
print(f"Satisfaction Rate: {df['satisfied'].mean() * 100:.2f}%")

Satisfaction Rate: 50.30%